# Use an official Node.js image as the base
FROM node:20

# Set the working directory to /app
WORKDIR /server

# Copy the package*.json files to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the application code to the working directory
COPY ./server ./server

RUN ls -la

EXPOSE 3000

CMD ["npm", "run", "server"]
